In [6]:
import numpy as np

X_Train =np.array([ [1,0,0,1,1,1],
            [1,1,0,1,1,1],
            [0,1,0,0,0,0],
            [0,0,1,0,0,1],
            [1,1,0,1,1,0],
            [0,1,0,1,1,0]
            ])

print(X_Train)

[[1 0 0 1 1 1]
 [1 1 0 1 1 1]
 [0 1 0 0 0 0]
 [0 0 1 0 0 1]
 [1 1 0 1 1 0]
 [0 1 0 1 1 0]]


In [7]:
yes_train = X_Train[:3,:]
print(yes_train)

[[1 0 0 1 1 1]
 [1 1 0 1 1 1]
 [0 1 0 0 0 0]]
