In [6]:
import numpy as np

X_Train =np.array([ [1,0,0,1,1,1],
            [1,1,0,1,1,1],
            [0,1,0,0,0,0],
            [0,0,1,0,0,1],
            [1,1,0,1,1,0],
            [0,1,0,1,1,0]
            ])

print(X_Train)

[[1 0 0 1 1 1]
 [1 1 0 1 1 1]
 [0 1 0 0 0 0]
 [0 0 1 0 0 1]
 [1 1 0 1 1 0]
 [0 1 0 1 1 0]]


In [8]:
yes_train = X_Train[:3,:]
print(yes_train)

[[1 0 0 1 1 1]
 [1 1 0 1 1 1]
 [0 1 0 0 0 0]]


In [9]:
yes_one_prob = yes_train.sum(axis= 0)/ yes_train.shape[0]
print(yes_one_prob)


[0.66666667 0.66666667 0.         0.66666667 0.66666667 0.66666667]


In [10]:
yes_zero_prob = 1 - yes_one_prob
print(yes_zero_prob)

[0.33333333 0.33333333 1.         0.33333333 0.33333333 0.33333333]
